### ISSUE TITLE
добавить в create_db.sql тестовые наборы данных для отладки

### ISSUE THREAD

**Issue by Baron-Munchhausen** [dim5x/PyNetHomeInvaderAlerter#28]

**Comment by dim5x** [comment]
Может быть использовать мой клиент? Добавление статических данных не решит проблему с двумя часами.

**Comment by Baron-Munchhausen** [comment]
> Может быть использовать мой клиент? Добавление статических данных не решит проблему с двумя часами.

Да, можно так.
Или объединить оба способа.
Заранее известные данные могут нам тоже понадобится, если вдруг решим реализовать unit-тесты.

**Comment by Baron-Munchhausen** [comment]
Перенес
- создание БД в метод create_db класса db_connection
- создание тестовых данных в отдельный скрипт debug_data.sql
- в config'е создал опцию debug: если значение не пустое, выполняется скрипт debug_data.sql
