### ISSUE TITLE
cicd

### ISSUE THREAD

**Issue by Baron-Munchhausen** [dim5x/PyNetHomeInvaderAlerter#6]
Скрипты для развертывания проекта из репозитория.
Например,
- устанавливается rsyslog, если не установлен
- заменяются конфигурационные файлы актуальными из репозитория

**Comment by dim5x** [comment]
В файле конфигурации не нужно ли раскомментировать это, для сбора данных по сети (UDP, 514)?
 #module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

**Comment by Baron-Munchhausen** [comment]
Закрываю как неактуальный пока.
